/** generated by Xtext 2.32.0 */
package fr.n7.pDL3.impl;

import fr.n7.pDL3.PDL3Package;
import fr.n7.pDL3.WorkSequences;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 *
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Work Sequences</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WorkSequencesImpl extends MinimalEObjectImpl.Container implements WorkSequences {
  /**
   *
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @generated
   */
  protected WorkSequencesImpl() {
    super();
  }

  /**
   *
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @generated
   */
  @Override
  protected EClass eStaticClass() {
    return PDL3Package.Literals.WORK_SEQUENCES;
  }
} // WorkSequencesImpl
