/** generated by Xtext 2.32.0 */
package fr.n7.pDL3;

/**
 *
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>The following features are supported:
 *
 * <ul>
 *   <li>{@link fr.n7.pDL3.Resource#getName <em>Name</em>}
 *   <li>{@link fr.n7.pDL3.Resource#getTotal <em>Total</em>}
 * </ul>
 *
 * @see fr.n7.pDL3.PDL3Package#getResource()
 * @model
 * @generated
 */
public interface Resource extends Resources {
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.pDL3.PDL3Package#getResource_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.Resource#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Total</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @return the value of the '<em>Total</em>' attribute.
   * @see #setTotal(int)
   * @see fr.n7.pDL3.PDL3Package#getResource_Total()
   * @model
   * @generated
   */
  int getTotal();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.Resource#getTotal <em>Total</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @param value the new value of the '<em>Total</em>' attribute.
   * @see #getTotal()
   * @generated
   */
  void setTotal(int value);
} // Resource
