/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL3;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Sequences</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.pDL3.PDL3Package#getWorkSequences()
 * @model
 * @generated
 */
public interface WorkSequences extends EObject
{
} // WorkSequences
