/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL3;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definitions</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.pDL3.PDL3Package#getWorkDefinitions()
 * @model
 * @generated
 */
public interface WorkDefinitions extends EObject
{
} // WorkDefinitions
