/** generated by Xtext 2.32.0 */
package fr.n7.pDL3;

/**
 *
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>The following features are supported:
 *
 * <ul>
 *   <li>{@link fr.n7.pDL3.WorkSequence#getLinkToPredecessor <em>Link To Predecessor</em>}
 *   <li>{@link fr.n7.pDL3.WorkSequence#getLinkType <em>Link Type</em>}
 *   <li>{@link fr.n7.pDL3.WorkSequence#getLinkToSucessor <em>Link To Sucessor</em>}
 * </ul>
 *
 * @see fr.n7.pDL3.PDL3Package#getWorkSequence()
 * @model
 * @generated
 */
public interface WorkSequence extends WorkSequences {
  /**
   * Returns the value of the '<em><b>Link To Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @return the value of the '<em>Link To Predecessor</em>' reference.
   * @see #setLinkToPredecessor(WorkDefinition)
   * @see fr.n7.pDL3.PDL3Package#getWorkSequence_LinkToPredecessor()
   * @model
   * @generated
   */
  WorkDefinition getLinkToPredecessor();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.WorkSequence#getLinkToPredecessor <em>Link To
   * Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @param value the new value of the '<em>Link To Predecessor</em>' reference.
   * @see #getLinkToPredecessor()
   * @generated
   */
  void setLinkToPredecessor(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Link Type</b></em>' attribute. The literals are from the
   * enumeration {@link fr.n7.pDL3.WorkSequenceKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @return the value of the '<em>Link Type</em>' attribute.
   * @see fr.n7.pDL3.WorkSequenceKind
   * @see #setLinkType(WorkSequenceKind)
   * @see fr.n7.pDL3.PDL3Package#getWorkSequence_LinkType()
   * @model
   * @generated
   */
  WorkSequenceKind getLinkType();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.WorkSequence#getLinkType <em>Link Type</em>}'
   * attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @param value the new value of the '<em>Link Type</em>' attribute.
   * @see fr.n7.pDL3.WorkSequenceKind
   * @see #getLinkType()
   * @generated
   */
  void setLinkType(WorkSequenceKind value);

  /**
   * Returns the value of the '<em><b>Link To Sucessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @return the value of the '<em>Link To Sucessor</em>' reference.
   * @see #setLinkToSucessor(WorkDefinition)
   * @see fr.n7.pDL3.PDL3Package#getWorkSequence_LinkToSucessor()
   * @model
   * @generated
   */
  WorkDefinition getLinkToSucessor();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.WorkSequence#getLinkToSucessor <em>Link To
   * Sucessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   *
   * @param value the new value of the '<em>Link To Sucessor</em>' reference.
   * @see #getLinkToSucessor()
   * @generated
   */
  void setLinkToSucessor(WorkDefinition value);
} // WorkSequence
