/*
 * generated by Xtext 2.32.0
 */
package fr.n7.validation;

/**
 * This class contains custom validation rules.
 *
 * <p>See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PDL3Validator extends AbstractPDL3Validator {

  //	public static final String INVALID_NAME = "invalidName";
  //
  //	@Check
  //	public void checkGreetingStartsWithCapital(Greeting greeting) {
  //		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
  //			warning("Name should start with a capital",
  //					PDL3Package.Literals.GREETING__NAME,
  //					INVALID_NAME);
  //		}
  //	}

}
