/*
 * generated by Xtext 2.32.0
 */
package fr.n7.scoping;

/**
 * This class contains custom scoping description.
 *
 * <p>See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping on how and
 * when to use it.
 */
public class PDL2ScopeProvider extends AbstractPDL2ScopeProvider {}
